namespace SportsBetting.DataCollector.Core.Entities;

/// <summary>
/// Represents a betting recommendation generated by the analysis engine.
/// </summary>
public class RecommendationEntity
{
    public Guid Id { get; set; }
    public Guid MatchId { get; set; }
    public string Market { get; set; } = string.Empty;
    public string Outcome { get; set; } = string.Empty;
    public string? Bookmaker { get; set; }
    public decimal OddDecimal { get; set; }
    public decimal ModelProbability { get; set; }
    public decimal? ImpliedProbability { get; set; }
    public decimal? Value { get; set; }
    public decimal? KellyFraction { get; set; }
    public decimal? StakeEuros { get; set; }
    public int? Confidence { get; set; }
    public string? Reasoning { get; set; }
    public string Status { get; set; } = "PENDING"; // PENDING, ACTIVE, SETTLED, CANCELLED
    public string? BetOutcome { get; set; } // WON | LOST | VOID
    public DateTime? OutcomeRecordedAt { get; set; }
    public string OutcomeSource { get; set; } = "manual"; // manual | auto
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    
    // Navigation property
    public MatchEntity? Match { get; set; }
    public BetEntity? Bet { get; set; }
}
